---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    fluxcd.io/automated: "true"
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: gitops-nginx
        image: abdessatar/gitops-nginx:1.5
        ports:
        - containerPort: 80
